receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      load:
      disk:

processors:
  resourcedetection:
    detectors: [system]
    system:
      hostname_sources: [os]
  batch:
    timeout: 5s
    send_batch_size: 100

exporters:
  kafka:
    brokers:
      - localhost:9092
    metrics:
      topic: otel-metrics
      encoding: otlp_json
    traces:
      topic: otel-traces
      encoding: otlp_json
    logs:
      topic: otel-logs
      encoding: otlp_json
  debug:
    verbosity: basic

service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [resourcedetection, batch]
      exporters: [kafka, debug]
    traces:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [kafka, debug]
    logs:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [kafka, debug]
