version: '3.3'
services:
  app-dev:
    container_name: blogvotingapp-dev
    build:
      context: ./
      dockerfile: dev.Dockerfile
    volumes:
      - ./src:/app/src
      - ./.m2:/root/.m2
    environment:
      - GRIDDB_NOTIFICATION_MEMBER=griddb-dev:10001
      - GRIDDB_CLUSTER_NAME=dockerGridDB
      - GRIDDB_USER=admin
      - GRIDDB_PASSWORD=admin
      - spring.thymeleaf.prefix=file:src/main/resources/templates/
    command: sh ./docker-entrypoint-dev.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    networks:
      - griddbvoting-dev-net
    depends_on:
      - griddb-dev
  griddb-dev:
    container_name: griddbvoting-dev
    build:
      context: ./griddbdocker
      dockerfile: Dockerfile531
    volumes:
      - griddbvoting-dev-vol:/var/lib/gridstore
    ports:
      - 10001:10001
      - 20001:20001
    networks:
      - griddbvoting-dev-net

networks:
  griddbvoting-dev-net:
volumes:
  griddbvoting-dev-vol: