name=griddb-test-sink
connector.class=com.github.griddb.kafka.connect.GriddbSinkConnector
tasks.max=1

host=
port=
cluster.name=gs_clustermfcloud8737
user=S01K7vrCuF-israel
password=israel
notification.member=
multicast=false

notification.provider.url=https://dbaassharemp1extconsta.blob.core.windows.net/dbaas-share-mp-extcon-blob/mfcloud8737.json?se=2046-04-15T17%3A32%3A54Z&sp=r&sv=2022-11-02&sr=b&sig=7jC1gx%2F0ZQG9I2LfDfoIl5XohRrTOlxp7kinmwU9qHs%3D

connection.route=PUBLIC
database=nl7QftSt

container.type=TIME_SERIES
topics.regex=metric_.*

# Coerce the int64 datetime field to a real Timestamp before sink mapping
transforms=TimestampConverter
transforms.TimestampConverter.type=org.apache.kafka.connect.transforms.TimestampConverter$Value
transforms.TimestampConverter.field=datetime
transforms.TimestampConverter.target.type=Timestamp
