###
GET  http://localhost:8080/httpbin/block/1
###
GET http://localhost:8080/httpbin/testCountMetrics
###
GET http://localhost:8080/httpbin/getVoteAggregateOverTime
###
GET http://localhost:8080/httpbin/getAllMetrics

###
POST http://localhost:8080/httpbin/vote/123
Content-Type: application/json

###
POST http://localhost:8080/blogs/api
Content-Type: application/json

{
  "title":"Blog Voting using Spring Boot and GridDB"
}
