apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: pv-azuredisk
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/4059eb9d-89c2-4add-8b00-6bfd7483864d/resourcegroups/mc_kubernetes-griddb_todogriddb_westus/providers/microsoft.compute/disks/myaksdisk
    volumeAttributes:
      fsType: ext4
