apiVersion: v1
kind: PersistentVolume
metadata:
  name: griddb-server-pv
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  hostPath:
    path: "/var/lib/gridstore/data"
