
services:
  griddb:
    container_name: griddb_server
    image: griddbnet/griddb:latest
    ports:
      - "10001:10001"
    healthcheck:
      test: ["CMD", "tail", "-f", "tail -f /var/lib/gridstore/log/gridstore*.log"]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    env_file:
      - .env
    container_name: image-gpt4-vision
    build: .
    ports:
      - "5115:5115"
    environment:
      - PORT=5115
      - HOST=localhost
    depends_on:
      - griddb