#!/bin/sh
### BEGIN INIT INFO
# Provides:          gridstore
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop GridDB server
### END INIT INFO

case "$1" in
start)
    echo "Starting Gridstore..."
    runuser -u gsadm -g gridstore -- /usr/griddb/bin/gridstore start
    ;;
stop)
    echo "Stopping Gridstore..."
    runuser -u gsadm -g gridstore -- /usr/griddb/bin/gridstore stop
    ;;
*)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
