[package]
name = "griddb_rust_client_blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
griddb = "0.6.0"
chrono = "0.4"
convert_case = "^0.3.0"
