input {
  file {
    path => "/Users/israelimru/logstash-demo/logs/nginx-access.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "nginx_access"
  }
}

filter {
  grok {
    match => {
      "message" => '%{IPORHOST:client_ip} - %{DATA:auth_user} \[%{HTTPDATE:log_timestamp}\] "%{WORD:http_method} %{DATA:request_path} HTTP/%{NUMBER:http_version}" %{NUMBER:response_code:int} %{NUMBER:response_bytes:int} "%{DATA:referrer}" "%{DATA:user_agent}"'
    }
  }

  date {
    match => [ "log_timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
    target => "@timestamp"
  }

  mutate {
    remove_field => [ "message", "log_timestamp", "event", "log", "@version", "host" ]
  }
}

output {
  stdout {
    codec => rubydebug
  }

  griddb {
    host        => "https://cloud8737.griddb.com:443"
    cluster     => ""
    database    => ""
    container   => "nginx_access_logs"
    username    => "israel"
    password    => "${GRIDDB_PASSWORD}"
    insert_mode => "append"
  }
}
