apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: webcontainer
          image: localhost:5000/web-server:02
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata: 
  name: web-server
  labels:
    app: web-server
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: web-server
    targetPort: 8000
  selector:
    app: web-server
