apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: authcontainer
          image: localhost:5000/auth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2828
---
apiVersion: v1
kind: Service
metadata: 
  name: auth
  labels:
    app: auth
spec:
  type: ClusterIP
  ports: 
  - port: 2828
    name: auth
    targetPort: 2828
  selector:
    app: auth
